info:
  contact: {}
paths:
  /user/CreateUser:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: password
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/DeleteUser:
    get:
      parameters:
      - description: id
        in: query
        name: id
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /user/UpdateUser:
    post:
      parameters:
      - description: id
        in: formData
        name: id
        type: string
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 修改用户
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户列表
      tags:
      - 用户模块
swagger: "2.0"
